services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
            - ./scans:/scans
        networks:
            - service_bridge    

    client:
        image: "ubuntu:21.04"
        command: [ "/bin/sh", "-c", "sleep infinity" ]  
        networks:
            - service_bridge            
        volumes:
            - ./scans:/scans
    
volumes:
    mongodb_data_container:

networks:
    service_bridge:
        driver: bridge        